### ISSUE TITLE
0.8.3 checklist

### ISSUE THREAD

**Issue by montyly** [crytic/slither#1172]
This a long-due release. We should aim to have it as soon as possible, but we will have April 22th as a strong deadline.

To do:
- [ ] Improve support for import alias (I have a local test failing, need a github issue)
- [ ] https://github.com/crytic/slither/issues/1019 (I have a local fix, need performance testing)
- [ ] https://github.com/crytic/slither/issues/1001
- [ ] https://github.com/crytic/slither/pull/1025
- [ ] https://github.com/crytic/slither/pull/1096
- [ ] https://github.com/crytic/slither/pull/1162
- [ ] https://github.com/crytic/slither/pull/968

Good to have:
- [ ] https://github.com/crytic/slither/pull/1134
- [ ] https://github.com/crytic/slither/pull/1022
