### ISSUE TITLE
Tracking: support for imports with alias (either symbol alias or unit alias)

### ISSUE THREAD

**Issue by SheldonHolmgren** [crytic/slither#1452]
### Describe the issue:

See the linked repo with a minimal reproducible example. Running `slither . --compile-force-framework foundry` leads to the crash with a backtrace pasted as the log output below. This is because Slither cannot find a contract named `c.Counter` (as referenced from `src/Importer.sol`).

If I edit Importer.sol in the following way:
```diff
diff --git a/src/Importer.sol b/src/Importer.sol
index 316a7e3..5fbc2fe 100644
--- a/src/Importer.sol
+++ b/src/Importer.sol
@@ -2,10 +2,10 @@
 // SPDX-License-Identifier: UNLICENSED
 pragma solidity ^0.8.13;
 
-import "src/Counter.sol" as c;
+import "src/Counter.sol";
 
 contract Importer {
     constructor() {
-        new c.Counter();
+        new Counter();
     }
 }
```
slither runs without problem.

### Code example to reproduce the issue:

https://github.com/SheldonHolmgren/slither_bug_example

### Version:

0.9.0

### Relevant log output:

```shell
'forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force' running
Compiling 19 files with 0.8.16
Solc 0.8.16 finished in 1.52s
Compiler run successful

Traceback (most recent call last):
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/__main__.py", line 97, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/__main__.py", line 75, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/slither.py", line 130, in __init__
    parser.analyze_contracts()
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 503, in analyze_contracts
    self._convert_to_slithir()
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 688, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/core/declarations/function.py", line 1705, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/core/cfg/node.py", line 719, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/slithir/convert.py", line 119, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/slithir/convert.py", line 1790, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/slithir/convert.py", line 438, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/slithir/convert.py", line 743, in propagate_types
    ir.lvalue.set_type(UserDefinedType(contract))
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/core/solidity_types/user_defined_type.py", line 24, in __init__
    assert isinstance(t, (Contract, Enum, Structure))
AssertionError
Error in .
Traceback (most recent call last):
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/__main__.py", line 826, in main_impl
    ) = process_all(filename, args, detector_classes, printer_classes)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/__main__.py", line 97, in process_all
    ) = process_single(compilation, args, detector_classes, printer_classes)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/__main__.py", line 75, in process_single
    slither = Slither(target, ast_format=ast, **vars(args))
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/slither.py", line 130, in __init__
    parser.analyze_contracts()
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 503, in analyze_contracts
    self._convert_to_slithir()
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/solc_parsing/slither_compilation_unit_solc.py", line 688, in _convert_to_slithir
    func.generate_slithir_and_analyze()
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/core/declarations/function.py", line 1705, in generate_slithir_and_analyze
    node.slithir_generation()
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/core/cfg/node.py", line 719, in slithir_generation
    self._irs = convert_expression(expression, self)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/slithir/convert.py", line 119, in convert_expression
    result = apply_ir_heuristics(result, node)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/slithir/convert.py", line 1790, in apply_ir_heuristics
    irs = propagate_type_and_convert_call(irs, node)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/slithir/convert.py", line 438, in propagate_type_and_convert_call
    new_ins = propagate_types(ins, node)
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/slithir/convert.py", line 743, in propagate_types
    ir.lvalue.set_type(UserDefinedType(contract))
  File "/home/holmgren/.local/lib/python3.10/site-packages/slither/core/solidity_types/user_defined_type.py", line 24, in __init__
    assert isinstance(t, (Contract, Enum, Structure))
AssertionError
```

**Comment by 0xalpharush** [comment]
Thanks for creating a repo for reproducing this. We also need to address https://github.com/crytic/slither/issues/1364

**Comment by 0xalpharush** [comment]
Example from here https://github.com/crytic/slither/issues/1536#issuecomment-1367227858

**Comment by 0xalpharush** [comment]
- [ ] https://github.com/crytic/slither/issues/1634
- [ ] https://github.com/crytic/slither/issues/1594
- [ ] https://github.com/crytic/slither/issues/1372
- [ ] https://github.com/crytic/slither/issues/1364

**Comment by 0xalpharush** [comment]
somewhat related https://github.com/crytic/slither/issues/1809

**Comment by preetisingh1121** [comment]
Made certain changes to address the issue : 

Changes to **solc_parsing/declarations/convert.py** : still getting error - 

ERROR:ContractSolcParsing:Impossible to generate IR for Importer.constructor (Importer.sol#9-12):
 'NoneType' object has no attribute 'references'

    # Provide an additional function for handling 'import ... as ...' 
    def parse_import_alias(self, stmt):
        import_alias_node = ast.AST.ImportAlias()
        import_alias_node.name = stmt['name']
        import_alias_node.alias = stmt['alias']
        return import_alias_node

    # Use the new function parse_import to check for the 'as' keyword
    def parse_import(self, stmt):
        import_node = ast.AST.Import()
        import_node.path = stmt['path']
        if 'as' in stmt:
            import_node.alias = self.parse_import_alias(stmt['as'])
        return import_node

**Comment by 0xAurelou** [comment]
Any work on going on this PR ?

**Comment by 0xalpharush** [comment]
Some work was started here but it is a large undertaking to get right and requires more testing https://github.com/crytic/slither/pull/2250

**Comment by 0xalpharush** [comment]
closed by https://github.com/crytic/slither/pull/2403
