### ISSUE TITLE
documentation tracking issue 

### ISSUE THREAD

**Issue by 0xalpharush** [crytic/slither#1859]
We should migrate away from github wiki and do the following:
- [ ] move detectors' wiki and detector table to auto-generated markdown in `docs`
- [ ] create a page for each printer and tool
- [ ] create architecture diagram for CONTRIBUTING.md
- [ ] enforce documentation style and add docs where they are missing
