### ISSUE TITLE
Flattening and etherscan upload

### ISSUE THREAD

**Issue by montyly** [crytic/slither#253]
Slither should be able to flatten any codebase and upload it to the etherscan verified contracts database, through [their API](https://etherscan.io/apis#contracts)

One caveat is to support aliasing of import

**Comment by montyly** [comment]
## Task Description
The goal is to create a new utility (ex: `slither-upload-etherscan`) that will:
- Takes as input a project and an address
- Flatten the codebase
- Upload the flatten code to etherscan verified contracts list

The [utility guideline](https://github.com/crytic/slither/wiki/Adding-a-new-utility) shows how to create new utility.

## Acceptance criteria
- Projects can be flattened and uploaded to etherscan
- The utility removes unnecessary import and pragma statements when flattening the code

A nice to have feature is the handling of import aliasing. 

## Required Skill
- Experience with Python 3.6
- Experience with Solidity smart contracts

No experience with Slither is required, but it would be a plus

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 150.0 DAI (150.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/253/3218).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/slither/253/3218).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $136,374.09 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [skyge](https://gitcoin.co/profile/skyge) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/slither/253/3218?mutate_worker_action=approve&worker=skyge) | [reject worker](https://gitcoin.co/issue/crytic/slither/253/3218?mutate_worker_action=reject&worker=skyge))_.**

I have experience with Python 3.6 and Solidity.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/253/3218).

**Comment by Skyge** [comment]
I am not sure, but for some have been verified contracts, they upload repeated pragma statements, such like this one: [cDAI](https://etherscan.io/address/0xf5dce57282a584d2746faf1593d3121fcac444dc#code)
so we want to remove these, Whether these have influence or not?

**Comment by montyly** [comment]
Hi @Skyge,

Thank you for your interest in this work. 

It's a good question. After some thinking, maybe we can offer an option like `--clean-code` that will for now, remove the unnecessary pragma statements. In the long run, this option could do other modifications, like re-ordering the contracts to improve the readability, etc. 

Does that make sense?

**Comment by Skyge** [comment]
OK, I see. That sounds good.

**Comment by ceresstation** [comment]
Hi @Skyge do you still have some time to take this one on, how's it going?

**Comment by Skyge** [comment]
@ceresstation Yeah, sorry for my delaying, I will finish this in three weeks.

**Comment by gitcoinbot** [comment]
@skyge Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=100)

**Comment by Skyge** [comment]
Hi, I want to find a file to save etherscan api key by this approach: 
```python
import os
os.environ['ETHERSCAN_API] = xxx
```

so which one has existed is suitable, if not, I will create a new file, or we would like to use some packages, such as `python-dotenv` or something else to do this in the `.env`.

**Comment by montyly** [comment]
Hi @Skyge ,

That's a potential solution, but I would favor another approach:

- Asking the key in an interactive mode, from the command line. 
- Having an option to provide the key through a config file. Most of the options in Slither are configurable through [json](https://github.com/crytic/slither/wiki/Usage#configuration-file), so it would make sense to keep this format.

I would favor the use of the interactive mode, to prevent the write of the key locally. Only people uploading frequently to etherscan should have to save the key.

**Comment by Skyge** [comment]
@montyly Emmm, but when we verify the contract by the etherscan api, we need some config message, such as, `compilerversion `, `optimizationUsed`, `constructorArguements` and so on, so if we use the interactive mode, the user really needs to type these necessary parameters, so I think maybe we can use a config file to add these config parameters. so what's your final recommendation?

**Comment by gitcoinbot** [comment]
@skyge Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=100)

**Comment by Skyge** [comment]
I made a temporary pr, it has not been finished totally.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@skyge due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/crytic/slither/253/3218) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/253/3218?snooze=100)

**Comment by igetgames** [comment]
Since this appears to be completd, would you mind closing out the [bounty on Gitcoin](https://gitcoin.co/issue/crytic/slither/253/3218)?

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__The funding of 150.0 DAI  (150.0 USD @ $1.0/DAI) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $128,402.96 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
