### ISSUE TITLE
Printer: constructor summary

### ISSUE THREAD

**Issue by montyly** [crytic/slither#271]
With multiple inheritances, it is sometimes difficult to follow the execution of the constructor. 
We should have a printer that outputs the solidity code executed at deployment

**Comment by montyly** [comment]
## Task Description
The goal is to create a new print that will
- [ ] Follow the C3 inheritance to create a view where all the executed constructor are showed
- [ ] Inline the internal calls

## Acceptance criteria
- [ ] The printer can show an inline version of the constructor(s)

## Required Skill
- [ ] Experience with Python 3.6
- [ ] Experience with Solidity smart contracts
- [ ] Experience with Slither

Feel free to ask questions here, or join our [slack](https://empireslacking.herokuapp.com/) (#ethereum)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 100.0 DAI (100.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/271/3216).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/slither/271/3216).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $135,881.77 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [abhimanyu121](https://gitcoin.co/profile/abhimanyu121) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/slither/271/3216?mutate_worker_action=approve&worker=abhimanyu121) | [reject worker](https://gitcoin.co/issue/crytic/slither/271/3216?mutate_worker_action=reject&worker=abhimanyu121))_.**

In the first step, I would get used to the codebase of Slither to work in a better manner, afterward, I would find and implement the most efficient way print name and details of the constructor that is being called.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/271/3216).

**Comment by Abhimanyu121** [comment]
Can I please get a little insight about c3 linearization(inheritance)?
It would help me a lot.

**Comment by gitcoinbot** [comment]
@abhimanyu121 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=100)

**Comment by gitcoinbot** [comment]
@abhimanyu121 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=100)

**Comment by gitcoinbot** [comment]
@abhimanyu121 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=100)

**Comment by gitcoinbot** [comment]
@abhimanyu121 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=100)

**Comment by Abhimanyu121** [comment]
Work in progress PR  has been submitted and I am waiting for the review from the maintainers.

**Comment by gitcoinbot** [comment]
@abhimanyu121 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=100)

**Comment by gitcoinbot** [comment]
@abhimanyu121 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=100)

**Comment by Abhimanyu121** [comment]
Work in progress PR has been submitted and I am waiting for the review from the maintainers.

**Comment by montyly** [comment]
Great work @Abhimanyu121, I merged https://github.com/crytic/slither/pull/299. thank you for the contribution.

@ceresstation can you pay the bounty? thx!

**Comment by Abhimanyu121** [comment]
@montyly  thank you for all your help :)

**Comment by gitcoinbot** [comment]
@abhimanyu121 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=100)

**Comment by Abhimanyu121** [comment]
awaiting bounty payment

**Comment by gitcoinbot** [comment]
@abhimanyu121 Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/271/3216?snooze=100)

**Comment by Abhimanyu121** [comment]
awaiting bounty

**Comment by montyly** [comment]
@ceresstation can you pay the bounty? Thank you.

**Comment by gitcoinbot** [comment]
⚡️ A tip worth 100.00000  DAI (100.0 USD @ $1.0/DAI) has been granted to @abhimanyu121 for this issue from @ceresstation. ⚡️ 

Nice work @abhimanyu121! Your tip has automatically been deposited in the ETH address we have on file.

 * $134354.88 in Funded OSS Work Available at: https://gitcoin.co/explorer
 * Incentivize contributions to your repo: <a href='https://gitcoin.co/tip'>Send a Tip</a> or <a href='https://gitcoin.co/funding/new'>Fund a PR</a>
 * No Email? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__This Bounty has been completed.__

Additional Tips for this Bounty:
* ceresstation tipped 100.0000 DAI worth 100.0 USD to abhimanyu121.

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/271/3216)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $134,354.88 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
