### ISSUE TITLE
Export Printer to JSON

### ISSUE THREAD

**Issue by montyly** [crytic/slither#286]
# Task Description

We want to add a printer output similar to our [JSON wrapping output](https://github.com/crytic/slither/blob/master/slither/__main__.py#L111-L126) for the detector 

- [ ] Classify the printer per output types (ex: text, dot generation, ...)
- [ ] Severalize the output to be sent through JSON
- [ ] Add the JSON printer output to our standard JSON

# Acceptance criteria
- [ ] Slither JSON output can contain any printer results
- [ ] An update of the [JSON documentation](https://github.com/crytic/slither/wiki/JSON-output) is prepared
- [ ] Unit tests for printers, based on the JSON output are prepared.

# Required Skills
- [ ] Experience with Python 3.6
- [ ] Experience with Solidity smart contracts
- [ ] Experience with Slither

This issue requires to discuss with me to design a proper output format and requires good programming skills.

Feel free to ask questions here, or join our [slack](https://empireslacking.herokuapp.com/) (#ethereum)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 200.0 DAI (200.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/286/3215).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/slither/286/3215).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $136,073.47 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 200.0 DAI (200.0 USD @ $1.0/DAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/286/3217).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/slither/286/3217).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $136,262.98 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by PumpkingWok** [comment]
Hi there,
I'm interest to take this bounty, right now i have not expressed interest for this bounty on gitcoin yet, I would like to take a look into slither code before. I have just looked into Json Wrapping code for detector. After having figured out properly the code I will take it via gitcoin if it will be still free.
Thanks in advance.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [man-jain](https://gitcoin.co/profile/man-jain) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/slither/286/3215?mutate_worker_action=approve&worker=man-jain) | [reject worker](https://gitcoin.co/issue/crytic/slither/286/3215?mutate_worker_action=reject&worker=man-jain))_.**

I have a good experience with Python and JSON, and can solve this issue.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/286/3215).

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [man-jain](https://gitcoin.co/profile/man-jain) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/slither/286/3215?mutate_worker_action=approve&worker=man-jain) | [reject worker](https://gitcoin.co/issue/crytic/slither/286/3215?mutate_worker_action=reject&worker=man-jain))_.**

I have a good experience with Python and JSON, and can solve this issue.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/286/3215).

**Comment by ceresstation** [comment]
Hi @man-jain glad to have you working on this, please try to make consistent WIP PRs and let us know if you run into any trouble.

**Comment by Man-Jain** [comment]
Thanks, I'll surely put up some consistent PRs. Also, it would be great if you could give a pointer from where I can begin the work.

**Comment by Man-Jain** [comment]
The outputs given by the various printers are basically of two types :- 1. .dot file 2. text. Also currently the printers aren't programmed yet to return output. So the first step would be to enable the printers to return outputs.(Please correct me if I am wrong)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [jamessandy](https://gitcoin.co/profile/jamessandy) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/slither/286/3217?mutate_worker_action=approve&worker=jamessandy) | [reject worker](https://gitcoin.co/issue/crytic/slither/286/3217?mutate_worker_action=reject&worker=jamessandy))_.**

Hello there, i've worked on similar project previously and i belive i can deliver in the least amount of time with minimal or no supervision if given just a chance .

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/286/3217).

**Comment by Man-Jain** [comment]
@ceresstation I have submitted a patch. Please see and give you feedback.

**Comment by Man-Jain** [comment]
@ceresstation Please check the output format and give your comment so that I can move forward with writing tests and documentation for this.

**Comment by gitcoinbot** [comment]
@man-jain Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
@man-jain Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by Man-Jain** [comment]
I am still working on this issue. But the work I intend to do depends upon [this](https://github.com/crytic/slither/pull/266) pr to be merged.

**Comment by gitcoinbot** [comment]
@man-jain Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
@man-jain Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by Man-Jain** [comment]
Yes Still working on it

**Comment by ceresstation** [comment]
Thanks for the update @Man-Jain could you provide a WIP PR if it makes sense to do so?

**Comment by gitcoinbot** [comment]
@man-jain Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
@man-jain Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by montyly** [comment]
For Gitcoin moderators: @Man-Jain has an ongoing PR and is waiting from a review from our side

**Comment by Man-Jain** [comment]
I have a open PR, waiting for review.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 10 months from now.
Please review their action plans below:


**1) [man-jain](https://gitcoin.co/profile/man-jain) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/slither/286/3215?mutate_worker_action=approve&worker=man-jain) | [reject worker](https://gitcoin.co/issue/crytic/slither/286/3215?mutate_worker_action=reject&worker=man-jain))_.**

It was showing that I had applied two  times because of which I was not able to participate in other bounties. I have already started the work and am in touch with the maintainers

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/286/3215).

**Comment by ceresstation** [comment]
@Man-Jain just wanted to check in to see how this is going, thanks!

**Comment by gitcoinbot** [comment]
@man-jain Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
@man-jain Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by Man-Jain** [comment]
Yes

**Comment by gitcoinbot** [comment]
@man-jain Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
@man-jain Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@man-jain due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/crytic/slither/286/3215) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@man-jain due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/crytic/slither/286/3215) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by ceresstation** [comment]
Hey @igetgames since we haven't heard back from @Man-Jain you're welcome to pick this up and complete it!

**Comment by montyly** [comment]
As the work did not progress, and this feature as a high priority for us, we end up working internally on it. 

@ceresstation can you close the bounty? Thanks!

**Comment by gitcoinbot** [comment]
@igetgames Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
@igetgames Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
@igetgames Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
@igetgames Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
@igetgames Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
@igetgames Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=1) | [3 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=3) | [5 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=5) | [10 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=10) | [100 days](https://gitcoin.co/issue/crytic/slither/286/3215?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 8 months from now.
Please review their action plans below:


**1) [igetgames](https://gitcoin.co/igetgames) has been approved to start work.**

I'd like to pick this up and complete it.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/286/3215).

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__The funding of 200.0 DAI  (200.0 USD @ $1.0/DAI) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $128,753.00 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Cancelled** 

<hr>

__The funding of 200.0 DAI  (200.0 USD @ $1.0/DAI) attached to this issue has been **cancelled** by the bounty submitter__

 
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $128,201.23 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by leekt216** [comment]
Is this implemented or not? I really want this feature
