### ISSUE TITLE
Split constant-function detector

### ISSUE THREAD

**Issue by montyly** [crytic/slither#318]
`constant-function` detects constant/view/pure functions changing the state or using assembly code.

We should split this into two detectors, and filter results if Solidity >=0.5 is used

**Comment by NicsTr** [comment]
Hi,
I'm interested in working on this issue.

When you say
> We should split this into two detectors

do you mean one detector for functions that are changing the state and one for functions using assembly code?
If I understood correctly, if Solidity >=0.5 is used, then the first detector is not needed because it is already enforced by the compiler, am I right?

**Comment by montyly** [comment]
## Task Description
Split the constant-function [detector](https://github.com/crytic/slither/blob/master/slither/detectors/attributes/const_functions.py) into two detectors
- One for constant functions changing the state
- One for constant functions with assembly code

Additionally, the detector does not report issue if solc>=0.5 is used.

## Acceptance criteria
- [ ] The detector is split into two detectors
- [ ] The unit tests are updated
- [ ] If solc >= 0.5 is used [self.slither.solc_version](https://github.com/crytic/slither/blob/master/slither/core/slither_core.py#L79-L83) (where `self` is the detector), the detector is disabled
## Required Skills
- [ ] Experience with Python 3.6
- [ ]  Experience with Solidity smart contracts
- [ ]  Experience with Slither


Feel free to ask questions here, or join our [slack](https://empireslacking.herokuapp.com/) (#ethereum)

**Comment by montyly** [comment]
Hi @NicsTr, thank you for your interest in this issue. I hope that the description above answers your question. 

You are right, the compiler since >=0.5 does enforce the `pure` and `view` attributes, so the detector is not needed.

We are creating a gitcoin bounty for this issue.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 100.0 SAI (100.0 USD @ $1.0/SAI)  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/318/3732).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/slither/318/3732).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $115,057.00 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 4 weeks, 1 day from now.
Please review their action plans below:


**1) [uivlis](https://gitcoin.co/uivlis) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/crytic/slither/318/3732?mutate_worker_action=approve&worker=uivlis) | [reject worker](https://gitcoin.co/issue/crytic/slither/318/3732?mutate_worker_action=reject&worker=uivlis))_.**

I will split the detector into one for state changing functions, disabled when solc version is >= 0.5, and into another one for functions containing assembly code.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/318/3732).

**Comment by karansinghgit** [comment]
@montyly I'd like to work on this issue.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 100.0 SAI (100.0 USD @ $1.0/SAI) has been submitted by__:

 1. [@uivlis](https://gitcoin.co/uivlis)



@ceresstation please take a look at the submitted work:
* [PR](https://github.com/crytic/slither/pull/379) by @uivlis

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/318/3732)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/crytic/slither/318/3732).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $100,166.08 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by montyly** [comment]
#379 and #380 are merged. Thanks @uivlis for the work.

@ceresstation can you pay the bounty? thx

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 100.0 SAI (100.0 USD @ $1.0/SAI)  attached to this issue has been approved & issued to @uivlis.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/crytic/slither/318/3732)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $100,596.93 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
