### ISSUE TITLE
0.6.14 checklist

### ISSUE THREAD

**Issue by montyly** [crytic/slither#676]
Expected release date: Week of November 9th

- [x] Fix github super linter support
- [x] Merge https://github.com/crytic/slither/pull/673
- [x] Update to crytic-compile 0.1.10 (https://github.com/crytic/crytic-compile/issues/118)
- [x] Write changelog

**Comment by montyly** [comment]
All the required pending PRs are done in crytic-compile and slither. I am planing the release for November 12th.
