### ISSUE TITLE
Slither 0.8.0 checklist

### ISSUE THREAD

**Issue by montyly** [crytic/slither#829]
Estimate: Week of April 26th

What is needed
- [x] Merge multiple compilation unit https://github.com/crytic/slither/pull/823 (breaking changes)
- [x] Fix https://github.com/crytic/slither/issues/820
- [x] Finish 0.8 support (UncheckedBlock) (https://github.com/crytic/slither/issues/795)
- [x] Fix https://github.com/crytic/slither/issues/768
- [ ] Investigate https://github.com/crytic/slither/issues/794
- [x] Open source new detectors

If the time permits:
- [ ] Create `slither-read-storage`: https://github.com/crytic/slither/issues/793
- [ ] Create `slither-log`: https://github.com/crytic/slither/issues/797

**Comment by montyly** [comment]
The release is ready. I will let all our tests run over the weekend, and if nothing major appears, we will have the release on Monday
