### ISSUE TITLE
Slither 0.8.1 checklist

### ISSUE THREAD

**Issue by montyly** [crytic/slither#905]
Date: Aiming for the week of August 9th, but might be the week after that depending on how much we can tackle these issues

- [ ] Review  https://github.com/crytic/slither/pull/895
- [ ] Review  https://github.com/crytic/slither/pull/896
- [x] Review https://github.com/crytic/slither/pull/903
- [x] Update documentation on configuration https://github.com/crytic/slither/issues/894
- [ ] Update taint example https://github.com/crytic/slither/issues/898
- [x] Fix typos https://github.com/crytic/slither/issues/892
- [ ] Add Yul support for top level functions https://github.com/crytic/slither/issues/899
