### ISSUE TITLE
New release checklist

### ISSUE THREAD

**Issue by montyly** [crytic/slither#979]
We are aiming to tackle as many issues as possible this week. We will release a new version on pypy by the beginning of next week

# Fix / missing features
- [x] https://github.com/crytic/slither/issues/962
- [x] https://github.com/crytic/slither/issues/944
- [x] https://github.com/crytic/slither/issues/899
- [x] https://github.com/crytic/slither/issues/919
- [x] Improve contrat name reused support (need a gh issue)
- [x] https://github.com/crytic/slither/issues/969

# New tools
- [x] https://github.com/crytic/slither/issues/793 (@0xalpharush)
- [ ] https://github.com/crytic/slither/issues/809
- [ ] https://github.com/crytic/slither/pull/939

# PRs to review
- [x] https://github.com/crytic/slither/pull/973
- [x] https://github.com/crytic/slither/pull/972
- [x] https://github.com/crytic/slither/pull/971
- [ ] https://github.com/crytic/slither/pull/968 (@0xalpharush)
- [x] https://github.com/crytic/slither/pull/967
- [x] https://github.com/crytic/slither/pull/964
- [x] https://github.com/crytic/slither/pull/947
- [ ] https://github.com/crytic/slither/pull/938
- [x] https://github.com/crytic/slither/pull/931
- [ ] https://github.com/crytic/slither/pull/935
- [x] https://github.com/crytic/slither/pull/921
- [x] https://github.com/crytic/slither/pull/920
